language: cpp

compiler:
  - gcc
  
env:
  matrix:
    - LINUX=1 TRAVIS_SHARED_LIBS=ON
    - LINUX=1 TRAVIS_SHARED_LIBS=OFF

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=$TRAVIS_SHARED_LIBS
  - make
    