language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug    TRAVIS_SHARED_LIBS=OFF  TRAVIS_STRICT_C90=OFF  TRAVIS_MAKE_CHECK=ON  TRAVIS_COVERALLS=ON
  - TRAVIS_BUILD_TYPE=Debug    TRAVIS_SHARED_LIBS=ON   TRAVIS_STRICT_C90=ON   TRAVIS_MAKE_CHECK=ON  TRAVIS_COVERALLS=OFF
  - TRAVIS_BUILD_TYPE=Release  TRAVIS_SHARED_LIBS=OFF  TRAVIS_STRICT_C90=OFF  TRAVIS_MAKE_CHECK=OFF TRAVIS_COVERALLS=OFF

script:
  - chmod +x travis-build-script.sh
  - ./travis-build-script.sh
