language: cpp

compiler:
  - gcc
  
env:
  matrix:
    - LINUX=1 TRAVIS_TRAVIS_SHARED_LIBS=ON
    - LINUX=1 TRAVIS_SHARED_LIBS=OFF

script:
  - mkdir debug && cd debug
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=$TRAVIS_SHARED_LIBS -DCMAKE_INSTALL_PREFIX=../install
  - make
  - make install
  -
  - cd .. && mkdir release && cd release
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=$TRAVIS_SHARED_LIBS -DCMAKE_INSTALL_PREFIX=../install
  - make install
  
