version: 0.1_build{build}

os: Visual Studio 2013

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

clone_folder: c:\projects\gmio.git

environment:
  matrix:
  - APPVEYOR_SHARED_LIBS: OFF
    APPVEYOR_CMAKE_GENERATOR: "Visual Studio 12 2013"

  - APPVEYOR_SHARED_LIBS: ON
    APPVEYOR_CMAKE_GENERATOR: "Visual Studio 12 2013"

build:

build_script:
 - cmake --version
 - cd c:\projects\gmio.git
 - mkdir build && cd build
 - ps: >-
     cmake -G %APPVEYOR_CMAKE_GENERATOR%
           -DCMAKE_BUILD_TYPE=%CONFIGURATION%
           -DCMAKE_DEBUG_POSTFIX=_d
           -DGMIO_BUILD_SHARED_LIBS=%APPVEYOR_SHARED_LIBS%
           -DGMIO_BUILD_EXAMPLES=ON
           -DGMIO_BUILD_BENCHMARKS=ON
           -DGMIO_BUILD_BENCHMARK_ASSIMP=OFF
           -DGMIO_BUILD_BENCHMARK_OPENCASCADE=OFF
           -DGMIO_BUILD_TESTS_FAKE_SUPPORT=ON
 - cmake --build .
