version: 0.4_build{build}

os: Visual Studio 2013

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

clone_folder: c:\projects\gmio.git

environment:
  matrix:
  - APPVEYOR_SHARED_LIBS: OFF
    APPVEYOR_CMAKE_GENERATOR: "Visual Studio 12 2013"
    APPVEYOR_FLOAT2STR_LIB: std

  - APPVEYOR_SHARED_LIBS: ON
    APPVEYOR_CMAKE_GENERATOR: "Visual Studio 12 2013"
    APPVEYOR_FLOAT2STR_LIB: google_doubleconversion

build:

build_script:
 - cmake --version
 - cd %APPVEYOR_BUILD_FOLDER%
 - mkdir build && cd build
 - cmake .. ^
         -G "%APPVEYOR_CMAKE_GENERATOR%"    ^
         -DCMAKE_BUILD_TYPE=%CONFIGURATION% ^
         -DCMAKE_DEBUG_POSTFIX=_d ^
         -DGMIO_BUILD_SHARED_LIBS=%APPVEYOR_SHARED_LIBS% ^
         -DGMIO_FLOAT2STR_LIB=%APPVEYOR_FLOAT2STR_LIB% ^
         -DGMIO_BUILD_EXAMPLES=ON   ^
         -DGMIO_BUILD_BENCHMARKS=ON ^
         -DGMIO_BUILD_BENCHMARK_ASSIMP=OFF ^
         -DGMIO_BUILD_BENCHMARK_LIB3MF=OFF ^
         -DGMIO_BUILD_BENCHMARK_OPENCASCADE=OFF ^
         -DGMIO_BUILD_TESTS_FAKE_SUPPORT=ON
 - cmake --build . --config %CONFIGURATION%
 - cmake --build . --target test_core --config %CONFIGURATION%
 - cmake --build . --target test_stl  --config %CONFIGURATION%
 - set PATH=%APPVEYOR_BUILD_FOLDER%\build\src\%CONFIGURATION%;%PATH%
 - cd tests && ctest . -V -C %CONFIGURATION%
